//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.08 at 02:46:41 PM QYZT 
//


package mn.partners.runtime.soap.dto.service;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mn.partners.runtime.soap.dto.service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetAllRoomPricesResponse_QNAME = new QName("http://partners.mn/runtime/soap", "GetAllRoomPricesResponse");
    private final static QName _HotelRoomPrice_QNAME = new QName("http://partners.mn/runtime/soap", "HotelRoomPrice");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mn.partners.runtime.soap.dto.service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllRoomPricesRequest }
     * 
     */
    public GetAllRoomPricesRequest createGetAllRoomPricesRequest() {
        return new GetAllRoomPricesRequest();
    }

    /**
     * Create an instance of {@link GetAllRoomPricesResponse }
     * 
     */
    public GetAllRoomPricesResponse createGetAllRoomPricesResponse() {
        return new GetAllRoomPricesResponse();
    }

    /**
     * Create an instance of {@link HotelRoomPrice }
     * 
     */
    public HotelRoomPrice createHotelRoomPrice() {
        return new HotelRoomPrice();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllRoomPricesResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetAllRoomPricesResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://partners.mn/runtime/soap", name = "GetAllRoomPricesResponse")
    public JAXBElement<GetAllRoomPricesResponse> createGetAllRoomPricesResponse(GetAllRoomPricesResponse value) {
        return new JAXBElement<GetAllRoomPricesResponse>(_GetAllRoomPricesResponse_QNAME, GetAllRoomPricesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HotelRoomPrice }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link HotelRoomPrice }{@code >}
     */
    @XmlElementDecl(namespace = "http://partners.mn/runtime/soap", name = "HotelRoomPrice")
    public JAXBElement<HotelRoomPrice> createHotelRoomPrice(HotelRoomPrice value) {
        return new JAXBElement<HotelRoomPrice>(_HotelRoomPrice_QNAME, HotelRoomPrice.class, null, value);
    }

}
