//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.26 at 09:50:32 AM QYZT 
//


package mn.partners.runtime.soap.dto.service;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mn.partners.runtime.soap.dto.service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mn.partners.runtime.soap.dto.service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllRoomPricesRequest }
     * 
     */
    public GetAllRoomPricesRequest createGetAllRoomPricesRequest() {
        return new GetAllRoomPricesRequest();
    }

    /**
     * Create an instance of {@link GetAllRoomPricesResponse }
     * 
     */
    public GetAllRoomPricesResponse createGetAllRoomPricesResponse() {
        return new GetAllRoomPricesResponse();
    }

    /**
     * Create an instance of {@link HotelRoomPrice }
     * 
     */
    public HotelRoomPrice createHotelRoomPrice() {
        return new HotelRoomPrice();
    }

}
