//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.26 at 09:50:32 AM QYZT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://partners.mn/runtime/soap", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package mn.partners.runtime.soap.dto.service;
