//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.08 at 02:46:41 PM QYZT 
//


package mn.partners.runtime.soap.dto.service;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoomType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="RoomType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="STANDARD"/&gt;
 *     &lt;enumeration value="SUPERIOR"/&gt;
 *     &lt;enumeration value="STUDIO"/&gt;
 *     &lt;enumeration value="FAMILY"/&gt;
 *     &lt;enumeration value="DELUXE"/&gt;
 *     &lt;enumeration value="SUITE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RoomType")
@XmlEnum
public enum RoomType {

    STANDARD,
    SUPERIOR,
    STUDIO,
    FAMILY,
    DELUXE,
    SUITE;

    public String value() {
        return name();
    }

    public static RoomType fromValue(String v) {
        return valueOf(v);
    }

}
