--liquibase formatted sql

        -- changeset diyar-java:1
        CREATE TABLE IF NOT EXISTS hotels (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR NOT NULL,
        address VARCHAR NOT NULL,
        CONSTRAINT unique_hotel UNIQUE (name, address));

        -- changeset diyar-java:2
        CREATE TABLE IF NOT EXISTS hotel_rooms (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        hotel_id INTEGER NOT NULL,
        price DECIMAL(10,2) CHECK (price >= 0),
        room_type VARCHAR NOT NULL,
        total_count_of_rooms INTEGER CHECK (total_count_of_rooms >= 0),
        reserved_rooms INTEGER CHECK (reserved_rooms >= 0 AND total_count_of_rooms >= reserved_rooms),
        CONSTRAINT fk_hotels_rooms FOREIGN KEY (hotel_id) REFERENCES hotels(id),
        CONSTRAINT unique_hotel_room UNIQUE (hotel_id, room_type));